---
- name: APP | Build app
  local_action:
    module: shell
    cmd: npm run build
    creates: dist/

- name: APP | Copy files
  become: no
  ansible.posix.synchronize:
    src: "{{ playbook_dir }}/../dist/"
    dest: "{{ root_path }}"
    recursive: yes
    owner: no
    group: no
    
- name: APP | Change config loader env
  replace:
    path: "{{ root_path }}/lib/config/parser.php"
    regexp: '\$this->env = "dev";'
    replace: '$this->env = "prod";'
    
- name: APP | Permissions
  shell: "chown -R www-data:www-data {{ root_path }} ; chmod -R u=rw,go=r {{ root_path }} ; chmod u=rwx,go=rx $(find {{ root_path }} -type d)"
  args:
    warn: false